"""Correcting columns in my tables

Revision ID: c5958ea62adb
Revises: ea56e0dec547
Create Date: 2025-05-30 23:25:14.928359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5958ea62adb'
down_revision: Union[str, None] = 'ea56e0dec547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_checks', sa.Column('hash', sa.String(), nullable=False))
    op.drop_column('password_checks', 'hash_prefix')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_checks', sa.Column('hash_prefix', sa.VARCHAR(), nullable=False))
    op.drop_column('password_checks', 'hash')
    # ### end Alembic commands ###
