"""initialise my tables in the database

Revision ID: ea2620968385
Revises: e1eaf06991d5
Create Date: 2025-05-28 15:00:47.767638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2620968385'
down_revision: Union[str, None] = 'e1eaf06991d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breachs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('breachDate', sa.String(), nullable=False),
    sa.Column('exposedData', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_checked', sa.String(), nullable=False),
    sa.Column('date_checked', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('no_of_breaches', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_prefix', sa.String(), nullable=False),
    sa.Column('checkedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('hash_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_breachs',
    sa.Column('mail_id', sa.Integer(), nullable=False),
    sa.Column('breach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breach_id'], ['breachs.id'], ),
    sa.ForeignKeyConstraint(['mail_id'], ['email_checks.id'], ),
    sa.PrimaryKeyConstraint('mail_id', 'breach_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_breachs')
    op.drop_table('password_checks')
    op.drop_table('email_checks')
    op.drop_table('users')
    op.drop_table('breachs')
    # ### end Alembic commands ###
